### ISSUE TITLE
Missing translation "Mark XP"/"XP marked" button

### ISSUE THREAD

**Issue by Andyvec** [patoarayas/dungeon-world-babele-es#7]
Hi!
I can see that the "Mark XP"/"XP marked" button hasn't been translate yet:
![image](https://user-images.githubusercontent.com/625233/167497302-95cb01ed-86c7-451f-b220-9d64ffea15d2.png)

PS: This translation is still being very useful to me, even it has been made for older Foundry VTT version. 
Many thanks for the hard work!

**Comment by mickypardo** [comment]
Hi!
I will try to fix it. 
Thanks

**Comment by mickypardo** [comment]
Is ready. Check it
